version: '2'
services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: esgi
      MYSQL_DATABASE: library
      MYSQL_USER: dev
      MYSQL_PASSWORD: esgi
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
  web:
    build: .
    container_name: php
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "80:80"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - db:db
      ports:
          - 8080:80
      environment:
          MYSQL_USER: dev
          MYSQL_PASSWORD: esgi
          MYSQL_ROOT_PASSWORD: esgi
volumes:
    persistent: